export const MapName = [
  "Ardenweald",
  "CaliforNia",
  "CrestFall",
  "IceCrown",
  "Maldraxxus",
  "Nazjatar",
  "NetherLands",
  "NewMexico",
  "OreGon",
  "OutLands",
  "PennsylVania",
  "Revendreth",
  "ShadowLands",
  "SnowBlossom",
  "WashingTon",
];

export const idx = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15];

export const owner = [
  "none",
  "none",
  "none",
  "none",
  "none",
  "none",
  "none",
  "none",
  "none",
  "none",
  "none",
  "none",
  "none",
  "none",
  "none",
];

export const topography = [
  "Mountain",
  "liver",
  "liver",
  "Mountain",
  "Mountain",
  "liver",
  "liver",
  "liver",
  "Mountain",
  "liver",
  "liver",
  "liver",
  "liver",
  "Mountain",
  "Mountain",
];

export const giveToken = [
  "5",
  "3",
  "3",
  "5",
  "5",
  "3",
  "3",
  "3",
  "5",
  "3",
  "3",
  "3",
  "3",
  "5",
  "5",
];

export const src = [
  "./img/Map/Ardenweald.png",
  "./img/Map/CaliforNia.png",
  "./img/Map/CrestFall.png",
  "./img/Map/IceCrown.png",
  "./img/Map/Maldraxxus.png",
  "./img/Map/Nazjatar.png",
  "./img/Map/NetherLands.png",
  "./img/Map/NewMexico.png",
  "./img/Map/OreGon.png",
  "./img/Map/OutLands.png",
  "./img/Map/PennsylVania.png",
  "./img/Map/Revendreth.png",
  "./img/Map/ShadowLands.png",
  "./img/Map/SnowBlossom.png",
  "./img/Map/WashingTon.png",
];
