export const name = [
  "대걸레",
  "라이온하트 너클",
  "막대기",
  "바스타드 소드",
  "빨간 지팡이",
  "손도끼",
  "앱솔랩스 단검",
  "앱솔랩스 너클",
  "앱솔랩스 소드",
  "앱솔랩스 튜너",
  "앱솔랩스 할버드",
  "장미칼",
  "제네시스 너클",
  "제네시스 소드",
  "제네시스 스태프",
  "죽창",
  "톱날검",
  "피노키오 코",
  "해적 검",
];
export const grade = [
  "C",
  "B",
  "C",
  "C",
  "C",
  "C",
  "B",
  "B",
  "B",
  "B",
  "B",
  "C",
  "A",
  "A",
  "A",
  "C",
  "C",
  "C",
  "C",
];
export const src = [
  "./img/Item/대걸레.png",
  "./img/Item/라이온하트 너클.png",
  "./img/Item/막대기.png",
  "./img/Item/바스타드소드.png",
  "./img/Item/빨간 지팡이.png",
  "./img/Item/손도끼.png",
  "./img/Item/앱솔랩스 단검.png",
  "./img/Item/앱솔랩스 블로우 너클.png",
  "./img/Item/앱솔랩스 소드.png",
  "./img/Item/앱솔랩스 튜너.png",
  "./img/Item/앱솔랩스 할버드.png",
  "./img/Item/장미칼.png",
  "./img/Item/제네시스 너클.png",
  "./img/Item/제네시스 소드.png",
  "./img/Item/제네시스 스태프.png",
  "./img/Item/죽창.png",
  "./img/Item/톱날검.png",
  "./img/Item/피노키오 코.png",
  "./img/Item/해적 검.png",
];
